# Generated by Django 4.0.1 on 2022-02-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='hosted',
            field=models.URLField(default='www.github.com'),
        ),
    ]
